### ISSUE TITLE
Custom Fields on customer create

### ISSUE THREAD

**Issue by MaxencePerrinPrestashop** [chargebee/chargebee-typescript#1]
Hi,

I want to create a new customer with a custom field (https://www.chargebee.com/docs/custom_fields.html), but i didnt find the custom field property on the _customer.create_params. 

How can i create a new customer with my customs fields ? 

Thank you !

**Comment by cb-navaneedhan** [comment]
@MaxencePerrinPrestashop You can create custom new customers with custom fields, like in the example: https://github.com/chargebee/chargebee-typescript#to-create-subscription-with-custom-headers-and-custom-fields using **param()** method

P.S: This example is written for creating subscriptions. You can follow the same way for creating customers also.

**Comment by Navaneedhan** [comment]
More details on `Custom Fields`: https://apidocs.chargebee.com/docs/api?lang=typescript#custom_fields

**Comment by cb-navaneedhan** [comment]
Closing this issue, as the usage description of custom fields has been added to the [apidocs](https://apidocs.chargebee.com/docs/api?lang=typescript#custom_fields)
