### ISSUE TITLE
Unable to open hosted page to update payment method

### ISSUE THREAD

**Issue by tuanlc** [chargebee/chargebee-typescript#13]
Hello ChargeBee  team,

I've encountered an issue when opening a hosted page to update the client's payment method. This is the response from ChargeBee:

```
{
   message: 'Update Payment Method is not supported for V3 Hosted pages',
   type: 'invalid_request',
   api_error_code: 'invalid_request',
   error_code: 'update_payment_method_not_supported_for_v3_hp',
   error_msg: 'Update Payment Method is not supported for V3 Hosted pages',
   http_status_code: 400
 }
```

As I checked, the version of Chargebee API that this library is used is `v2`. So, could you please tell me why did I get this error?
I'm kindly looking forward to you soon. Thank you!

**Comment by CJohnson25** [comment]
I am also running into the same issue. using v2 of the api, and v2.0.8 of this project.

**Comment by CJohnson25** [comment]
Was able to solve the problem by using the manage_payment_sources method. It seems documentation does mention this. 
https://apidocs.chargebee.com/docs/api/hosted_pages#update_payment_method

**Comment by cb-rakesh** [comment]
> Hello ChargeBee team,
> 
> I've encountered an issue when opening a hosted page to update the client's payment method. This is the response from ChargeBee:
> 
> ```
> {
>    message: 'Update Payment Method is not supported for V3 Hosted pages',
>    type: 'invalid_request',
>    api_error_code: 'invalid_request',
>    error_code: 'update_payment_method_not_supported_for_v3_hp',
>    error_msg: 'Update Payment Method is not supported for V3 Hosted pages',
>    http_status_code: 400
>  }
> ```
> 
> As I checked, the version of Chargebee API that this library is used is `v2`. So, could you please tell me why did I get this error?
> I'm kindly looking forward to you soon. Thank you!

Are you still facing this issue? If not, can we close this?

**Comment by tuanlc** [comment]
Hello,
No, I am not. I resolved the issue by checking more documentation from ChargeBee about the payment source and 3DS.
I will close this ticket.
Thank you!
