### ISSUE TITLE
unable to use chargebee typescript due to missing modules

### ISSUE THREAD

**Issue by tanzeelrana** [chargebee/chargebee-typescript#16]
ERROR in ./node_modules/chargebee-typescript/lib/core.js
Module not found: Error: Can't resolve 'http' in '/Users/tanzeel.rehman/Development/chargebee/node_modules/chargebee-typescript/lib'

ERROR in ./node_modules/chargebee-typescript/lib/core.js
Module not found: Error: Can't resolve 'https' in '/Users/tanzeel.rehman/Development/chargebee/node_modules/chargebee-typescript/lib'

ERROR in ./node_modules/chargebee-typescript/lib/core.js
Module not found: Error: Can't resolve 'os' in '/Users/tanzeel.rehman/Development/chargebee/node_modules/chargebee-typescript/lib'

**Comment by evelina-max** [comment]
Hi, any update regarding this issue? Any advice how to solve?

**Comment by arminrosu** [comment]
Posting for posterity:

@tanzeelrana it seems like your bundler / tsconfig.json is not configured for node and it's complaining about node's built-in [https](https://nodejs.org/api/https.html) module.

**Comment by cb-rakesh** [comment]
Closing this as this doesn't seem to be related to chargebee-typescript package.

**Comment by murtaza-farooqi89** [comment]
i am having the same issue.

**Comment by che-wavefin** [comment]
Having the same issue, can't run on a react project. Has someone figured out how to solve this?
