### ISSUE TITLE
Missing data in list endpoint

### ISSUE THREAD

**Issue by jesseyay** [chargebee/chargebee-typescript#22]
Hi team at Chargebee,

While using this API to call the list endpoint for item prices:

```
. . .
const result = await chargebee.item_price.list().request();
. . .
```

The resulting data includes a list that has the correct _number_ of items but no data in each item, they are all empty objects. Looks something like this:
```
{ list: [ {},{},{},{} ] }
```

The `hosted_pages/checkout_new_for_items` equivalent also has the same issue.

I've used the library for other endpoints which works fine.

On version `2.3.0`

Unless I am missing something important I think this is a bug.

**Comment by cb-khushbubibay** [comment]
Hi @jesseyay ,
We tested it from dev end and getting proper response for both item_prices and hosted_pages/checkout_new_for_items, it might be a data issue at your end.
Requesting you to please check once again and provide us Curl response for these API calls if possible.

**Comment by ifeelfishy** [comment]
Hi @jesseyay , have a look at #14 (https://github.com/chargebee/chargebee-typescript/pull/14).

**Comment by cb-khushbubibay** [comment]
Hi @jesseyay 
We have tested this for both versions v2.3.0 and v2.4.0, and it's working fine for all APIs mentioned by you. If you are still facing this issue, please reopen.
