### ISSUE TITLE
Applying coupons when creating subscription not working

### ISSUE THREAD

**Issue by bluetiger1008** [chargebee/chargebee-typescript#29]
Create subscription actually works but coupons are not applied though I send coupon_ids as params like this:
chargebee.subscription.create_with_items("xxxxx", {
"subscription_items":[{"item_price_id":"xxxxx","unit_price":418800}],
"coupon_ids":["TROOM"]
});

Is this bug of this library or chargebee backend issue?

**Comment by bluetiger1008** [comment]
I tested post man, and I see coupon_ids is added. so I think this is issue in this library.

**Comment by cb-prajaktachavan** [comment]
Hi, This issue is fixed in v2.7.1 so closing this issue.
