### ISSUE TITLE
Errors running this lib

### ISSUE THREAD

**Issue by dimmank** [chargebee/chargebee-typescript#3]
Hey there!
I'm trying to use this lib but I'm getting a lot of errros.

WARNING in C:\Projects\tokeep\trunk\portal\src\app\components\account\manage-account\manage-account.component.ts depends on 'chargebee-typescript'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

ERROR in ./node_modules/chargebee-typescript/lib/core.js
Module not found: Error: Can't resolve 'http' in 'C:\Projects\tokeep\trunk\portal\node_modules\chargebee-typescript\lib'

ERROR in ./node_modules/chargebee-typescript/lib/core.js
Module not found: Error: Can't resolve 'https' in 'C:\Projects\tokeep\trunk\portal\node_modules\chargebee-typescript\lib'

ERROR in ./node_modules/chargebee-typescript/lib/core.js
Module not found: Error: Can't resolve 'os' in 'C:\Projects\tokeep\trunk\portal\node_modules\chargebee-typescript\lib'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\pagefile.sys'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\swapfile.sys'
Error from chokidar (C:\node_modules): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'
Error from chokidar (C:\node_modules): Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'
Error from chokidar (C:\node_modules): Error: EBUSY: resource busy or locked, lstat 'C:\pagefile.sys'
Error from chokidar (C:\node_modules): Error: EBUSY: resource busy or locked, lstat 'C:\swapfile.sys'
Error from chokidar (C:\node_modules): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log

I'm using Angular v.10 (~10.0.10)
Is there a workaround or does this lib need to be updated?

Cheers! Dimitri

**Comment by cb-navaneedhan** [comment]
@dimmank Would you mind sharing the `tsconfig.json`, that you have for building the app ?
or could you please share the details of `module` and `target` type used for compiling your typescript app ?

**Comment by dimmank** [comment]
Hi! My app is built with the latest version of angular-cli. 

Steps to reproduce:

1: Install angular-cli and run the create new app script:
2. npm install -g @angular/cli
3. ng new my-dream-app
4. open the directory (my-dream-app) in VS-code and run your install command in the console
 npm install chargebee-typescript@">=2"
5.
add this code to app.component

import { Component, OnInit } from '@angular/core';

import { ChargeBee } from 'chargebee-typescript';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {
  title = 'my-dream-app';

  ngOnInit(): void {
     const chargebee = new ChargeBee();
  }
}

6. run ng serve
Error occurs in console as above

Thanks!

**Comment by cb-navaneedhan** [comment]
Hi @dimmank , thank you for the detailed repro steps:

Please add the following to your `package.json` and try it out.

```
"browser": {
    "https": false,
    "http": false,
    "os": false
  }
```

**Comment by dimmank** [comment]
Thanks!
This is so strange, the settings in the package.json file seem to be working in the project as described above, but not in my actual project.

This works:
{
  "name": "my-dream-app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "browser": {
    "https": false,
    "http": false,
    "os": false
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~10.0.9",
    "@angular/common": "~10.0.9",
    "@angular/compiler": "~10.0.9",
    "@angular/core": "~10.0.9",
    "@angular/forms": "~10.0.9",
    "@angular/platform-browser": "~10.0.9",
    "@angular/platform-browser-dynamic": "~10.0.9",
    "@angular/router": "~10.0.9",
    "chargebee-typescript": "^2.0.1",
    "rxjs": "~6.5.5",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1000.6",
    "@angular/cli": "~10.0.6",
    "@angular/compiler-cli": "~10.0.9",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~3.3.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.9.5"
  }
}

This does not work:

{
  "name": "my-production-app",
  "version": "1.0.0",
  "scripts": {
    "ng": "ng",
    "postinstall": "ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points",
    "start": "ng serve --o",
    "build": "ng build --prod --base-href=/portal/",
    "lint": "ng lint",
    "generate": "swagger-angular-generator -s src/api/swagger.json -d src/app/services"
  },
  "browser": {
    "https": false,
    "http": false,
    "os": false
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~10.0.10",
    "@angular/cdk": "^10.1.3",
    "@angular/common": "~10.0.10",
    "@angular/compiler": "~10.0.10",
    "@angular/core": "~10.0.10",
    "@angular/forms": "~10.0.10",
    "@angular/material": "^10.1.3",
    "@angular/platform-browser": "~10.0.10",
    "@angular/platform-browser-dynamic": "~10.0.10",
    "@angular/router": "~10.0.10",
    "@angular/service-worker": "~10.0.10",
    "@ngrx/effects": "^10.0.0",
    "@ngrx/entity": "^10.0.0",
    "@ngrx/schematics": "^10.0.0",
    "@ngrx/store": "^10.0.0",
    "angular-auth-oidc-client": "^11.2.0",
    "chargebee-typescript": "^2.0.1",
    "moment": "^2.27.0",
    "rxjs": "~6.6.2",
    "swagger-angular-generator": "^4.2.2",
    "tslib": "^2.0.1",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1000.5",
    "@angular/cli": "~10.0.5",
    "@angular/compiler-cli": "~10.0.10",
    "@types/node": "^14.0.27",
    "@types/jasmine": "~3.5.12",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^6.0.0-next.1",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.1.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.1",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.10.2",
    "tslint": "~6.1.3",
    "typescript": "~3.9.7"
  }
}

**Comment by dimmank** [comment]
The project (my-dream-app) is throwing an error in the console when running this code:

import { Component, OnInit } from '@angular/core';

import { ChargeBee } from 'chargebee-typescript';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {
  title = 'my-dream-app';

  ngOnInit(): void {
    const chargebee = new ChargeBee();

    // chargebee.configure({
    //   site: 'tokeep-test',
    //   api_key: 'test_T61KxuDSCVf0rvhCMtNs8CaDN2IC2yAa'
    // });

    chargebee.configure({
      site: 'mannar-test',
      api_key: 'test___dev__2d2aopx6Dh6tzq5qI3FuV7TuWMbxaudy'
    });
    chargebee.subscription.create({
      plan_id: 'basic',
      auto_collection: 'off',
      billing_address: {
        first_name: 'John',
        last_name: 'Doe',
        line1: 'PO Box 9999',
        city: 'Walnut',
        state: 'California',
        zip: '91789',
        country: 'US'
      },
      customer: {
        first_name: 'John',
        last_name: 'Doe',
        email: 'john@user.com'
      }
    }).request((error, result) => {
      if (error) {
        // handle error
        console.log(error);
      } else {
        console.log(`${result}`);
        const subscription: typeof chargebee.subscription = result.subscription;
        const customer: typeof chargebee.customer = result.customer;
        const card: typeof chargebee.card = result.card;
        const invoice: typeof chargebee.invoice = result.invoice;
        const unbilled_charges: Array<typeof chargebee.unbilled_charge> = result.unbilled_charges;
      }
    });

  }

}

The error is:
ERROR ReferenceError: Buffer is not defined
    at Function.makeApiRequest (core.js:58)
    at RequestWrapper.request (request_wrapper.js:60)

**Comment by dimmank** [comment]
I'm using the cod from the front-end/angular example instead

**Comment by anderslyman** [comment]
@dimmank I'm getting the same error - where did you find the front-end/angular example?

**Comment by dimmank** [comment]
@anderslyman 
I found it here:
https://github.com/chargebee/chargebee-checkout-samples/tree/master/api/front-end/angular
