### ISSUE TITLE
ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by soukalp** [chargebee/chargebee-typescript#37]
Hi all,

I solved a problem with **'Typescript issue with webpack < 5'** first. And now I am getting this **'ReferenceError: Buffer is not defined'** when I am trying to call **'this.chargebee.hosted_page.checkout_new_for_items'**. Do you have any idea how to solve this?

I tried everything what is mentioned here, but it doesn't work. https://stackoverflow.com/questions/68707553/uncaught-referenceerror-buffer-is-not-defined

Node version 16.16.0, Angular version 16.1.5

**Comment by cb-alish** [comment]
Hi @soukalp, can you please share more details on how you’re using hosted_page.checkout_new_for_items?

**Comment by cb-alish** [comment]
Hi @soukalp, can you please let us know if you are still facing this issue?

**Comment by cb-sriramthiagarajan** [comment]
Hi @soukalp, I'm closing this issue for now. Please open a new issue if you're still facing this.
