### ISSUE TITLE
[Question] What is the difference between chargebee-node and chargebee-typescript - and which one to use?

### ISSUE THREAD

**Issue by JanThiel** [chargebee/chargebee-typescript#51]
Hey there,

let's make it quick: What is the difference between the `chargebee-node` and `chargebee-typescript` projects and packages?

From what I get: Once upon a time the `chargebee-typescript` project was the only one supporting ... typescript ;-). But now as far as I can see the `chargebee-node` does offer full(?) Typescript support as well.

Any insights? And suggestions which package to use?

Thank you very much :-)

**Comment by cb-sriramthiagarajan** [comment]
Hey @JanThiel , you're absolutely right 😄.  We started providing TS typings with the `chargebee-node` package fairly recently.

We're also thinking of consolidating these into a single package and archive the other. This is still under discussion. We'll make an announcement with all the details in both the repos + other places when we make that decision. For now, I'd suggest you go with [chargebee](https://npmjs.com/package/chargebee) but you'd be good to pick either of these.

**Comment by cb-sriramthiagarajan** [comment]
@JanThiel — I see from #50 that you're planning to use [chargebee-typescript](https://npmjs.com/package/chargebee-typescript) and I wanted to say that it should be fine. The reason I suggested [chargebee](https://npmjs.com/package/chargebee) in my previous comment was that if we're decide on consolidating, we'll likely be using that package (mainly for the name!) but that shouldn't affect your decision.

**Comment by JanThiel** [comment]
@cb-sriramthiagarajan The feedback regarding the `os` module and Edge support in #50 applies to the `chargebee-node` package as well.

We switched our integration to `chargebee-node` already following your suggestion that this will be the leading project and package anyway.

**Comment by cb-sriramthiagarajan** [comment]
Closing this issue since we've discussed and answered the main question.
