### ISSUE TITLE
Broken function TypeScript types in version `2.34.0`

### ISSUE THREAD

**Issue by ihmpavel** [chargebee/chargebee-typescript#55]
After upgrading from `2.33.0` to `2.34.0` return types are broken.

Working `2.33.0`:
```
type CustomerRetrieveInput = Parameters<typeof Customer.retrieve>
type CustomerRetrieveOutput = Promise<{
  card: Card
  customer: Customer
}>
const customerRetrieve = (
  customerId: CustomerRetrieveInput[0],
  params?: CustomerRetrieveInput[1]
): CustomerRetrieveOutput => chargebee.customer.retrieve(customerId, params).request()
```

Not working `2.34.0` - same code.
Issue:
<img width="952" alt="image" src="https://github.com/chargebee/chargebee-typescript/assets/42217494/e834b3f0-4a0e-479f-999a-4e34cc461bac">

---
One liner:
<img width="757" alt="image" src="https://github.com/chargebee/chargebee-typescript/assets/42217494/bfc68b5f-a465-481f-bf14-6c4dcc7f13ad">

---

After looking into the changes made https://github.com/chargebee/chargebee-typescript/commit/8a4e9fa1a886565705650ac72120aa0842a73dc0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R23-L27 it looks like the problem is changing `@types/q` from `devDependencies` to `dependencies`.

**Comment by cb-alish** [comment]
Hi @ihmpavel , thanks for reporting this and sorry for the trouble. We’ve reverted the change which caused this issue for now. Please try `v2.35.0` and let us know if you still face any issue.

**Comment by ihmpavel** [comment]
Hi @cb-alish, with `2.35.0` everything works now!

Thanks
