### ISSUE TITLE
What's the difference between this and chargebee-node with TypeScript?

### ISSUE THREAD

**Issue by brunobely** [chargebee/chargebee-typescript#58]
It seems like chargebee-node supports TS, so when should I be using that or this library?

https://github.com/chargebee/chargebee-node?tab=readme-ov-file#usage-with-typescript

**Comment by cb-sriramthiagarajan** [comment]
Thanks for the question @brunobely.

Yes, `chargebee-node` supports TS and there's quite a bit of duplication between `chargebee-node` and `chargebee-typescript`. We've had this for legacy reasons and had this question before, #51 for example. To address this, we're soon releasing v3 of `chargebee-node` which is currently in [beta](https://www.npmjs.com/package/chargebee/v/3.0.0-beta.4) and deprecate this package (with enough time for existing users to migrate)

You can look at the announcement post on #57. It'd be great if you could give the beta version a try and share your feedback.

**Comment by brunobely** [comment]
Thanks for the quick response! Not sure how I missed those two issues 😅

**Comment by cb-sriramthiagarajan** [comment]
Cool, no worries. 3.x is stable now and we'd love to hear if you have any feedback.
