### ISSUE TITLE
[Types] Add return types to api requests

### ISSUE THREAD

**Issue by L-U-C-K-Y** [chargebee/chargebee-typescript#7]
Hi Chargebee Team

Thank you for adding typescript support, it's a huge help for us already!

Currently, the API methods in the library do not have return types and are all wrapped in the `RequestWrapper` class.
While working, it passes on quite a big part where Typescript can help us to develop more safely and efficiently.

I would appreciate if you add return types to all API calls.

Thanks and kind regards

Lucky

**Comment by ibratoev** [comment]
The current TypeScript implementation is of amazingly bad quality. Not having typed return types defeats the whole purpose of using TypeScript.

**Comment by sebastien-lb** [comment]
Hello ChargeBee Team ! 
Do you plan to add the return types of the API in the lib? I think this is a huge use case of the API. 
Thanks :)

**Comment by cb-khushbubibay** [comment]
This has been merged in v2.4.0.

**Comment by ifeelfishy** [comment]
> This has been merged in v2.4.0.

Has it? How do we access them?

**Comment by ralph-remo** [comment]
I don't see the return types as well - everything's still returning `RequestWrapper` types.

**Comment by ibratoev** [comment]
@cb-khushbubibay The types were not really added. Looking at the commit (https://github.com/chargebee/chargebee-typescript/commit/24c3398b08dbcf5f166abf583ecaf0872ce57997) it just adds `RequestWrapper` explicitly for the return type. This is not what this 1+ year issue is about. It is about typing the actual return types. Please, reopen.

**Comment by wodka** [comment]
Hi, I've just created a PR as it is really annoying to not have types on the requests. I did update all places that were returning a RequestWrapper and extended RequestWrapper to per default return a Model

**Comment by L-U-C-K-Y** [comment]
@cb-khushbubibay @cb-rakesh @cb-goutham @cb-yateshmathuria @cb-navaneedhan

Please review, fix and merge the PR from @wodka (great username btw). 

Having a 'RequestWrapper' return type on its own is useless. 

Thanks!
