### ISSUE TITLE
Does anyone have this successfully working in the browser?

### ISSUE THREAD

**Issue by anderslyman** [chargebee/chargebee-typescript#8]
This library is written for node.js.
Refer: https://github.com/chargebee/chargebee-typescript/blob/master/src/core.ts
It requires `http`, `https`, `os`.

Does anyone have this working in the browser?
I got this far:
```
import {Buffer} from 'buffer';
import {Core} from 'chargebee-typescript/lib/core';

(window as any).global = window;
(window as any).global.Buffer = (window as any).global.Buffer || Buffer;
(window as any).process = {version: '3.9.5'};
(Core as any).os = {
  platform() {
    return 'browser';
  },
  arch() {
    return 'x86';
  },
  release() {
    return '1';
  }
};
```

How did you shim/polyfill the http/https pieces for the `request` function?

**Comment by sagar7993** [comment]
@anderslyman This library is specifically made to be used in a nodejs backend environment, and cannot be used in frontend code. If you want to integrate chargebee on your frontend, you'll have to use the [chargebee checkout](https://www.chargebee.com/docs/checkout.html) script.

There is NO installable npm package for this yet and the only officially supported way as of now is to include their script in your index.html and using the window.Chargebee object for initiating the checkout
